#pragma once

enum {
    REPORT_ID_KEYBOARD = 1,
    REPORT_ID_LIGHTING_LAMP_ARRAY_ATTRIBUTES, // 2
    REPORT_ID_LIGHTING_LAMP_ATTRIBUTES_REQUEST, // 3
    REPORT_ID_LIGHTING_LAMP_ATTRIBUTES_RESPONSE, // 4
    REPORT_ID_LIGHTING_LAMP_MULTI_UPDATE, // 5 
    REPORT_ID_LIGHTING_LAMP_RANGE_UPDATE, // 6
    REPORT_ID_LIGHTING_LAMP_ARRAY_CONTROL, // 7
    REPORT_ID_COUNT
};
